# Exception Handling

try:
    print(10 / 0)
# except ZeroDivisionError as e:
except Exception as e:
    print("Error: Division by Zero")
